package com.hdlee.pdfnote;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.pdf.PdfRenderer;
import android.net.Uri;
import android.os.*;
import android.provider.OpenableColumns;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;

public class MainActivity extends Activity implements PdfPageView.Listener {
    private static final int OPEN_PDF=10, EXPORT_JSON=11, NAVY=0xFF173B63, ACCENT=0xFF2563EB;
    private PdfRenderer renderer; private ParcelFileDescriptor descriptor; private Uri documentUri;
    private String documentTitle="PDF"; private int currentPage, selectedColor=0x66FFDE59;
    private PdfPageView pageView; private TextView titleView,pageLabel; private Button highlightButton;
    private ImageButton bookmarkButton,colorButton,memoButton,fullscreenExit; private LinearLayout header,bottomBar;
    private FrameLayout root; private AnnotationStore store; private boolean highlightMode,memoMode,fullscreen;
    private SharedPreferences recentPrefs;

    @Override protected void onCreate(Bundle state){super.onCreate(state);store=new AnnotationStore(this);recentPrefs=getSharedPreferences("recent_documents",MODE_PRIVATE);buildUi();Uri u=getIntent().getData();if(u!=null)openPdf(u);else showWelcome();}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private ImageButton icon(int image,String label,int tint,View.OnClickListener click){ImageButton b=new ImageButton(this);b.setImageResource(image);b.setColorFilter(tint);b.setContentDescription(label);b.setBackgroundColor(Color.TRANSPARENT);b.setScaleType(ImageView.ScaleType.CENTER);b.setPadding(dp(12),dp(12),dp(12),dp(12));b.setOnClickListener(click);return b;}

    private void buildUi(){
        root=new FrameLayout(this);root.setBackgroundColor(0xFFF1F3F5);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new FrameLayout.LayoutParams(-1,-1));
        header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(4),0,dp(4),0);header.setBackgroundColor(NAVY);
        header.addView(icon(R.drawable.ic_folder_open,"PDF 열기",Color.WHITE,v->choosePdf()),new LinearLayout.LayoutParams(dp(52),dp(56)));
        titleView=new TextView(this);titleView.setTextColor(Color.WHITE);titleView.setTextSize(19);titleView.setSingleLine();titleView.setGravity(Gravity.CENTER_VERTICAL);titleView.setPadding(dp(8),0,dp(8),0);header.addView(titleView,new LinearLayout.LayoutParams(0,dp(56),1));
        header.addView(icon(R.drawable.ic_fullscreen,"전체 화면",Color.WHITE,v->toggleFullscreen()),new LinearLayout.LayoutParams(dp(48),dp(56)));
        header.addView(icon(R.drawable.ic_more_vert,"도구",Color.WHITE,v->showTools()),new LinearLayout.LayoutParams(dp(48),dp(56)));content.addView(header,new LinearLayout.LayoutParams(-1,dp(56)));
        pageView=new PdfPageView(this,this);content.addView(pageView,new LinearLayout.LayoutParams(-1,0,1));
        bottomBar=new LinearLayout(this);bottomBar.setGravity(Gravity.CENTER_VERTICAL);bottomBar.setPadding(dp(4),dp(4),dp(4),dp(4));bottomBar.setBackgroundColor(Color.WHITE);bottomBar.setElevation(dp(10));
        bottomBar.addView(icon(R.drawable.ic_chevron_left,"이전 페이지",NAVY,v->showPage(currentPage-1)),new LinearLayout.LayoutParams(dp(44),dp(56)));
        pageLabel=new TextView(this);pageLabel.setGravity(Gravity.CENTER);pageLabel.setTextColor(0xFF475569);pageLabel.setTextSize(14);pageLabel.setSingleLine();pageLabel.setBackground(round(0xFFF1F5F9,18));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(38),1);pp.setMargins(dp(2),0,dp(2),0);bottomBar.addView(pageLabel,pp);
        bottomBar.addView(icon(R.drawable.ic_chevron_right,"다음 페이지",NAVY,v->showPage(currentPage+1)),new LinearLayout.LayoutParams(dp(44),dp(56)));
        highlightButton=new Button(this);highlightButton.setText("하이라이트");highlightButton.setTextSize(13);highlightButton.setTextColor(NAVY);highlightButton.setAllCaps(false);highlightButton.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_highlight,0,0,0);highlightButton.setCompoundDrawablePadding(dp(4));highlightButton.setBackground(round(0xFFEFF6FF,18));highlightButton.setOnClickListener(v->toggleHighlight());LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-2,dp(42));hp.setMargins(dp(4),0,dp(4),0);bottomBar.addView(highlightButton,hp);
        colorButton=icon(R.drawable.ic_palette,"하이라이트 색상",NAVY,v->chooseColor());bottomBar.addView(colorButton,new LinearLayout.LayoutParams(dp(46),dp(46)));updateColorButton();
        memoButton=icon(R.drawable.ic_note_add,"메모 추가",NAVY,v->toggleMemoMode());bottomBar.addView(memoButton,new LinearLayout.LayoutParams(dp(44),dp(56)));
        bookmarkButton=icon(R.drawable.ic_star_outline,"즐겨찾기",NAVY,v->toggleBookmark());bottomBar.addView(bookmarkButton,new LinearLayout.LayoutParams(dp(48),dp(56)));content.addView(bottomBar,new LinearLayout.LayoutParams(-1,dp(64)));
        fullscreenExit=icon(R.drawable.ic_fullscreen_exit,"전체 화면 종료",Color.WHITE,v->toggleFullscreen());fullscreenExit.setBackground(round(0xAA0F172A,24));fullscreenExit.setVisibility(View.GONE);FrameLayout.LayoutParams ep=new FrameLayout.LayoutParams(dp(48),dp(48),Gravity.TOP|Gravity.END);ep.setMargins(0,dp(12),dp(12),0);root.addView(fullscreenExit,ep);
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets b=insets.getInsets(WindowInsets.Type.systemBars());top=b.top;bottom=b.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}if(!fullscreen){header.setPadding(dp(4),top,dp(4),0);header.getLayoutParams().height=dp(56)+top;bottomBar.setPadding(dp(4),dp(4),dp(4),dp(4)+bottom);bottomBar.getLayoutParams().height=dp(64)+bottom;}return insets;});setContentView(root);
    }
    private void showWelcome(){titleView.setText("PDF Note");pageLabel.setText("PDF를 열어 시작하세요");String u=recentPrefs.getString("last_uri",null);if(u!=null)new AlertDialog.Builder(this).setTitle("최근 문서").setMessage(recentPrefs.getString("last_title","최근 PDF")+"을 다시 여시겠습니까?").setPositiveButton("열기",(d,w)->openPdf(Uri.parse(u))).setNegativeButton("다른 문서",(d,w)->choosePdf()).show();}
    private void choosePdf(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/pdf");startActivityForResult(i,OPEN_PDF);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==OPEN_PDF){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}openPdf(u);}else if(req==EXPORT_JSON){try(OutputStream out=getContentResolver().openOutputStream(u)){if(out!=null)out.write(store.exportJson(documentUri,documentTitle).getBytes());toast("주석을 내보냈습니다");}catch(Exception e){toast("내보내기 실패: "+e.getMessage());}}}
    private void openPdf(Uri u){closePdf();try{descriptor=getContentResolver().openFileDescriptor(u,"r");if(descriptor==null)throw new IOException("파일을 읽을 수 없습니다");renderer=new PdfRenderer(descriptor);documentUri=u;documentTitle=queryName(u);titleView.setText(documentTitle);store.open(u);recentPrefs.edit().putString("last_uri",u.toString()).putString("last_title",documentTitle).apply();showPage(0);}catch(Exception e){closePdf();toast("PDF 열기 실패: "+e.getMessage());showWelcome();}}
    private String queryName(Uri u){try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception ignored){}return u.getLastPathSegment()==null?"PDF":u.getLastPathSegment();}
    private void showPage(int index){if(renderer==null||index<0||index>=renderer.getPageCount())return;currentPage=index;try(PdfRenderer.Page page=renderer.openPage(index)){int width=Math.max(1080,getResources().getDisplayMetrics().widthPixels*2);float ratio=Math.min(2.5f,(float)width/page.getWidth());Bitmap image=Bitmap.createBitmap((int)(page.getWidth()*ratio),(int)(page.getHeight()*ratio),Bitmap.Config.ARGB_8888);image.eraseColor(Color.WHITE);Matrix m=new Matrix();m.postScale(ratio,ratio);page.render(image,null,m,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);pageView.showPage(image,index,store.marks);pageLabel.setText((index+1)+" / "+renderer.getPageCount());updateBookmarkButton();}}
    private void toggleHighlight(){if(renderer==null)return;highlightMode=!highlightMode;memoMode=false;updateToolStates();pageView.setMemoMode(false);pageView.setHighlightMode(highlightMode,selectedColor);toast(highlightMode?"문장을 따라 좌우로 드래그하세요":"하이라이트를 종료했습니다");}
    private void toggleMemoMode(){if(renderer==null)return;memoMode=!memoMode;highlightMode=false;updateToolStates();pageView.setHighlightMode(false,selectedColor);pageView.setMemoMode(memoMode);toast(memoMode?"메모를 놓을 위치를 탭하세요":"메모 추가를 종료했습니다");}
    private void updateToolStates(){highlightButton.setText(highlightMode?"하이라이트 ✓":"하이라이트");highlightButton.setTextColor(highlightMode?Color.WHITE:NAVY);highlightButton.setBackground(round(highlightMode?ACCENT:0xFFEFF6FF,18));memoButton.setColorFilter(memoMode?Color.WHITE:NAVY);memoButton.setBackground(memoMode?round(ACCENT,22):round(Color.TRANSPARENT,22));}
    private void updateColorButton(){GradientDrawable d=new GradientDrawable();d.setShape(GradientDrawable.OVAL);d.setColor(selectedColor|0xFF000000);d.setStroke(dp(3),Color.WHITE);colorButton.setBackground(d);colorButton.setColorFilter(Color.WHITE);}
    private void chooseColor(){String[] names={"선샤인","민트","로즈","스카이","라벤더"};int[] colors={0x66FFDE59,0x6654C27A,0x66FF6B9A,0x66549CF5,0x66B67CF2};LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(22),dp(6),dp(22),dp(18));TextView guide=new TextView(this);guide.setText("PDF 위에 표시할 색상을 선택하세요");guide.setTextColor(0xFF64748B);guide.setTextSize(14);guide.setPadding(0,0,0,dp(18));panel.addView(guide);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);panel.addView(row,new LinearLayout.LayoutParams(-1,-2));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("하이라이트 색상").setView(panel).setNegativeButton("취소",null).create();for(int i=0;i<colors.length;i++){final int c=colors[i];ImageButton s=new ImageButton(this);s.setContentDescription(names[i]);GradientDrawable bg=new GradientDrawable();bg.setShape(GradientDrawable.OVAL);bg.setColor(c|0xFF000000);bg.setStroke(dp(c==selectedColor?4:1),c==selectedColor?NAVY:0xFFE2E8F0);s.setBackground(bg);s.setOnClickListener(v->{selectedColor=c;pageView.setHighlightMode(highlightMode,selectedColor);updateColorButton();dialog.dismiss();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(46),dp(46),1);p.setMargins(dp(4),0,dp(4),0);row.addView(s,p);}dialog.show();}
    private void toggleBookmark(){if(renderer==null)return;if(!store.bookmarks.add(currentPage))store.bookmarks.remove(currentPage);store.save();updateBookmarkButton();}
    private void updateBookmarkButton(){boolean marked=renderer!=null&&store.bookmarks.contains(currentPage);bookmarkButton.setImageResource(marked?R.drawable.ic_star:R.drawable.ic_star_outline);bookmarkButton.setColorFilter(marked?0xFFF59E0B:NAVY);bookmarkButton.setContentDescription(marked?"즐겨찾기 해제":"즐겨찾기 추가");}
    private void toggleFullscreen(){fullscreen=!fullscreen;header.setVisibility(fullscreen?View.GONE:View.VISIBLE);bottomBar.setVisibility(fullscreen?View.GONE:View.VISIBLE);fullscreenExit.setVisibility(fullscreen?View.VISIBLE:View.GONE);if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);if(fullscreen)c.hide(WindowInsets.Type.systemBars());else c.show(WindowInsets.Type.systemBars());}}else getWindow().getDecorView().setSystemUiVisibility(fullscreen?View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION:View.SYSTEM_UI_FLAG_VISIBLE);root.requestApplyInsets();}
    @Override public void onBackPressed(){if(fullscreen)toggleFullscreen();else super.onBackPressed();}
    @Override public void onHighlightCreated(AnnotationStore.Mark mark){store.marks.add(mark);store.save();pageView.invalidate();}
    @Override public void onMemoPointRequested(int page,float x,float y){EditText input=new EditText(this);input.setHint("메모를 입력하세요");input.setPadding(dp(24),dp(12),dp(24),dp(12));new AlertDialog.Builder(this).setTitle("새 메모").setView(input).setPositiveButton("저장",(d,w)->{String note=input.getText().toString().trim();if(note.isEmpty())return;AnnotationStore.Mark m=new AnnotationStore.Mark();m.page=page;m.left=Math.max(0f,x-0.025f);m.right=Math.min(1f,x+0.025f);m.top=Math.max(0f,y-0.025f);m.bottom=Math.min(1f,y+0.025f);m.color=selectedColor;m.note=note;m.noteOnly=true;store.marks.add(m);store.save();pageView.invalidate();toast("파란 메모 표시를 탭하면 수정하거나 삭제할 수 있습니다");}).setNegativeButton("취소",null).show();}
    @Override public void onMarkTapped(AnnotationStore.Mark mark){editMark(mark);}
    private void editMark(AnnotationStore.Mark mark){EditText input=new EditText(this);input.setHint("메모를 입력하세요");input.setText(mark.note);input.setPadding(dp(24),dp(12),dp(24),dp(12));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("페이지 "+(mark.page+1)+(mark.noteOnly?" 메모":" 하이라이트")).setIcon(R.drawable.ic_delete).setView(input).setPositiveButton("저장",(d,w)->{mark.note=input.getText().toString().trim();store.save();pageView.invalidate();}).setNegativeButton(mark.noteOnly?"메모 삭제":"하이라이트 삭제",(d,w)->{store.marks.remove(mark);store.save();pageView.invalidate();toast(mark.noteOnly?"메모를 삭제했습니다":"하이라이트를 삭제했습니다");}).setNeutralButton("취소",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(0xFFD32F2F));dialog.show();}
    private void showTools(){String[] t={"전체 화면","메모·하이라이트 목록","즐겨찾기 목록","페이지로 이동","주석 백업(JSON)","사용법"};new AlertDialog.Builder(this).setTitle("도구").setItems(t,(d,w)->{if(w==0)toggleFullscreen();else if(w==1)showMarkList();else if(w==2)showBookmarks();else if(w==3)goToPage();else if(w==4)exportAnnotations();else showHelp();}).show();}
    private void showMarkList(){List<AnnotationStore.Mark> items=new ArrayList<>(store.marks);if(items.isEmpty()){toast("저장된 하이라이트나 메모가 없습니다");return;}String[] labels=new String[items.size()];for(int i=0;i<items.size();i++){String note=items.get(i).note;labels[i]="p."+(items.get(i).page+1)+"  "+(note==null||note.isEmpty()?"(메모 없음)":note);}new AlertDialog.Builder(this).setTitle("메모·하이라이트").setItems(labels,(d,i)->{showPage(items.get(i).page);editMark(items.get(i));}).show();}
    private void showBookmarks(){if(store.bookmarks.isEmpty()){toast("즐겨찾기한 페이지가 없습니다");return;}List<Integer> pages=new ArrayList<>(store.bookmarks);Collections.sort(pages);String[] labels=new String[pages.size()];for(int i=0;i<pages.size();i++)labels[i]="페이지 "+(pages.get(i)+1);new AlertDialog.Builder(this).setTitle("즐겨찾기").setItems(labels,(d,i)->showPage(pages.get(i))).show();}
    private void goToPage(){if(renderer==null)return;EditText input=new EditText(this);input.setInputType(2);input.setHint("1 ~ "+renderer.getPageCount());new AlertDialog.Builder(this).setTitle("페이지로 이동").setView(input).setPositiveButton("이동",(d,w)->{try{showPage(Integer.parseInt(input.getText().toString())-1);}catch(Exception ignored){toast("올바른 페이지를 입력하세요");}}).setNegativeButton("취소",null).show();}
    private void exportAnnotations(){if(documentUri==null)return;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,documentTitle.replaceAll("(?i)\\.pdf$","")+"_annotations.json");startActivityForResult(i,EXPORT_JSON);}
    private void showHelp(){new AlertDialog.Builder(this).setTitle("PDF Note 사용법").setMessage("• 열기: 왼쪽 위 폴더 아이콘\n• 하이라이트: 버튼을 누르고 문장을 좌우로 드래그\n• 색상: 컬러 원을 눌러 선택\n• 메모: 메모 아이콘을 누른 뒤 원하는 위치를 탭\n• 메모 수정·삭제: PDF의 파란 메모 표시를 탭\n• 확대: 두 손가락으로 핀치\n• 전체 화면: 위쪽 확장 아이콘\n• 즐겨찾기: 별 아이콘\n\n하이라이트와 메모는 서로 별개로 저장되며 원본 PDF는 변경하지 않습니다.").setPositiveButton("확인",null).show();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void closePdf(){if(renderer!=null){renderer.close();renderer=null;}if(descriptor!=null)try{descriptor.close();}catch(IOException ignored){}descriptor=null;}
    @Override protected void onDestroy(){closePdf();super.onDestroy();}
}
